public class Commands{

	public static final String NEWHAND = "NEWHAND"
	public static final String SET_BUTTON = "SET BUTTON {1}"
	public static final String ADD_PLAYER = "ADD PLAYER {2}"
	public static final String ANTE = "ANTE {1} {2}"
	public static final String SMALL_BLIND = "SMALL BLIND {1} {2}"
	public static final String BIG_BLIND = "BIG BLIND {1} {2}"
	public static final String SMALL_AND_BIG_BLINDS = "SMALL AND BIG BLINDS {1} {2}"
	public static final String DEAL_CARDS = "DEAL CARDS {1} {2}"
	public static final String CALL = "CALL {1} {2}"
	public static final String FOLD = "FOLD {1}"
	public static final String RAISE = "RAISE {1} {2} to {3}"
	public static final String BETS = "BETS {1} {2}"
	public static final String CHECK = "CHECK {1}"
	public static final String MUCK = "MUCK {1}"
	public static final String LEAVE_TABLE = "LEAVE TABLE {1}"
	public static final String JOIN_TABLE = "JOIN TABLE {1} {2}"
	public static final String COLLECTED_FROM_POT = "COLLECTED FROM POT {1} {2}"
	public static final String COLLECTED_FROM_POT = "COLLECTED FROM POT {1} {2}"
	public static final String COLLECTED_FROM_SIDE_POT = "COLLECTED FROM SIDE POT {1} {2}"
	public static final String COLLECTED_FROM_SIDE_POT = "COLLECTED FROM SIDE POT {1} {2}"
	public static final String FLOP = "FLOP {1}"
	public static final String TURN = "TURN {2}"
	public static final String RIVER = "RIVER {2}"
}